import { Brain, Cloud, Layers } from "lucide-react";

export const services = [
  {
    icon: Cloud,
    title: "Systems",
    problem: "Change is blocked by brittle integration, unclear boundaries, and rising operational load.",
    description: "Stabilise interfaces, deployment, and operational control so change ships without regressions or surprise load.",
    features: ["Interfaces + integration", "Budgets + telemetry", "Guardrails + rollout", "Runbooks + handover"],
    caseStudy: "/case-studies/bigquery-optimization",
    highlight: "Baselines + guardrails",
    outcome: "Predictable change with lower operational load.",
    why: "Modernisation fails when systems cannot be operated or changed safely.",
    ifDonePoorly: "You get brittle glue code, surprise costs, and regressions that erode trust.",
    notFit: "Not a fit when you do not own production operation or the problem is not yet in production.",
  },
  {
    icon: Brain,
    title: "Intelligence",
    problem: "Information overload drives manual triage, slow decisions, and inconsistent outcomes.",
    description: "Apply retrieval and decision support where it measurably reduces human load, with explicit constraints and controlled data access.",
    features: ["Retrieval + summarisation", "Evaluation + regression checks", "Auditable behaviour", "Controlled data access"],
    caseStudy: "/case-studies/ai-recipe-platform",
    highlight: "Evaluation-first",
    outcome: "Useful outputs with known limits.",
    why: "Intelligence only matters when behaviour is measurable, explainable, and safe to run.",
    ifDonePoorly: "You get plausible outputs, silent failure, and risk in audit and security.",
    notFit: "Not a fit when the required data cannot be accessed, governed, or monitored.",
  },
  {
    icon: Layers,
    title: "Product",
    problem: "Operators work around the tooling, and every release adds new failure modes.",
    description: "Build operator-facing tooling that matches real workflows, with performance budgets, clear ownership, and safe releases.",
    features: ["Operator-first workflows", "Performance budgets", "Maintainable foundations", "Safe releases"],
    caseStudy: "/case-studies/ai-recipe-platform",
    highlight: "Operability-first",
    outcome: "Tools people adopt and keep.",
    why: "Modernisation needs an interface people will use. Without it, change stalls.",
    ifDonePoorly: "You get brittle UI, slow releases, and shadow processes.",
    notFit: "Not a fit when workflows and ownership are not defined.",
  },
];
