import { Brain, Cloud, Layers } from "lucide-react";

export const services = [
  {
    id: "cloud",
    icon: Cloud,
    title: "Cloud Architecture & Infrastructure",
    problem: "Change is blocked by brittle infrastructure, unclear ownership, and rising operational load.",
    description: "Stabilise interfaces, deployment, and run-time control so change ships without regressions or surprise spend.",
    features: ["Baselines + telemetry", "Guardrails + rollout", "SLOs + alerting", "Runbooks + handover"],
    caseStudy: "/case-studies/bigquery-optimization",
    highlight: "Baselines + guardrails",
    outcome: "Predictable change with lower operational load.",
    why: "Modernisation fails when systems cannot be operated or changed safely.",
    ifDonePoorly: "You get brittle glue code, surprise costs, and regressions that erode trust.",
    notFit: "Not a fit when you do not own production operation or the problem is not yet in production.",
  },
  {
    id: "ai",
    icon: Brain,
    title: "Applied AI & Machine Learning",
    problem: "Models ship without evaluation, drift detection, or a plan for failure in production.",
    description: "Apply AI where it measurably reduces human load, with explicit constraints, baselines, and safe fallbacks.",
    features: ["Evaluation + drift checks", "Fallbacks + guardrails", "Auditable behaviour", "Serving budgets"],
    caseStudy: "/case-studies/ai-recipe-platform",
    highlight: "Evaluation-first",
    outcome: "Useful outputs with known limits.",
    why: "Intelligence only matters when behaviour is measurable, explainable, and safe to run.",
    ifDonePoorly: "You get plausible outputs, silent failure, and risk in audit and security.",
    notFit: "Not a fit when the required data cannot be accessed, governed, or monitored.",
  },
  {
    id: "fullstack",
    icon: Layers,
    title: "Full-Stack Development",
    problem: "Operators work around the tooling, and every release adds new failure modes.",
    description: "Build operator-facing tools with performance baselines, clear ownership, and safe releases.",
    features: ["Operator-first workflows", "Performance baselines", "Observable critical paths", "Safe releases"],
    caseStudy: "/case-studies/ai-recipe-platform",
    highlight: "Operability-first",
    outcome: "Tools people adopt and keep.",
    why: "Modernisation needs an interface people will use. Without it, change stalls.",
    ifDonePoorly: "You get brittle UI, slow releases, and shadow processes.",
    notFit: "Not a fit when workflows and ownership are not defined.",
  },
];
